### PR TITLE
Fix wrong link to mapping page

### LINKED ISSUE #23: Import page help link goes to wrong page
`columns can be adjusted in the Coupon Import Mapping section.` goes to the wrong page

### PR DESCRIPTION
**Pull request by mihaijoldis**
Fixes #23

### CODE REVIEW

**Comment by LisaCee** [comment]
It looks like the url may have changed to `edit.php?post_type=download&page=edd-settings&tab=extensions&section=coupon_importer`.

**Comment by ashleyfae** [comment]
Yeah this link should actually be doing to Downloads > Settings > Extensions > Coupon Importer.

@mihaijoldis You can either update this or let us know if you want us to take over.

**Comment by mihaijoldis** [comment]
@mihaijoldis updated PR

**Review by ashleyfae — APPROVED** [review]
Thank you! :raised_hands:

**Pull request merged**
